name: Upload Data to HF

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  data-upload:
    runs-on: ubuntu-latest
    environment: huggingface
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: do the heavy lifting
        run: python main.py ${{secrets.API_TOKEN}}
